-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS public.authors
(
    id bigint NOT NULL,
    username character varying(250) COLLATE pg_catalog."default",
    name character varying(250) COLLATE pg_catalog."default",
    signature text COLLATE pg_catalog."default",
    create_time integer,
    verified boolean,
    ftc boolean,
    relation integer,
    open_favorite boolean,
    comment_setting integer,
    duet_setting smallint,
    stitch_setting smallint,
    private_account boolean,
    secret boolean,
    is_ad_virtual boolean,
    download_setting smallint,
    recommend_reason character varying(250) COLLATE pg_catalog."default",
    suggest_account_bind boolean,
    CONSTRAINT authors_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.hashtags
(
    name character varying(250) COLLATE pg_catalog."default" NOT NULL,
    id bigint,
    type smallint,
    sub_type smallint,
    is_commerce boolean,
    description text COLLATE pg_catalog."default",
    CONSTRAINT hashtags_pkey PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public.music
(
    id bigint NOT NULL,
    title character varying(250) COLLATE pg_catalog."default",
    author_name character varying(250) COLLATE pg_catalog."default",
    original boolean,
    schedule_search_time integer,
    collected boolean,
    precise_duration json,
    CONSTRAINT music_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.scrape_logs
(
    seed_id bigint NOT NULL,
    scraped_last timestamp without time zone,
    downloaded_video boolean,
    encountered_error character varying(1) COLLATE pg_catalog."default",
    CONSTRAINT scrape_logs_pkey PRIMARY KEY (seed_id)
);

CREATE TABLE IF NOT EXISTS public.video_files
(
    id bigint NOT NULL,
    filepath text COLLATE pg_catalog."default" NOT NULL,
    duration integer,
    height integer,
    width integer,
    ratio integer,
    volume_loudness numeric(3, 1),
    volume_peak numeric(6, 5),
    has_original_audio boolean,
    enable_audio_caption boolean,
    no_caption_reason smallint,
    is_slide boolean,
    CONSTRAINT video_files_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.videos
(
    id bigint NOT NULL,
    time_created timestamp without time zone,
    author_id bigint,
    description text COLLATE pg_catalog."default",
    hashtags character varying(250)[] COLLATE pg_catalog."default",
    mentions bigint[],
    music_id bigint,
    schedule_time integer,
    location_created character varying(2) COLLATE pg_catalog."default",
    is_ad boolean,
    suggested_words character varying(250)[] COLLATE pg_catalog."default",
    diggcount integer,
    sharecount integer,
    commentcount integer,
    playcount integer,
    collectcount integer,
    repostcount integer,
    poi_name character varying(250) COLLATE pg_catalog."default",
    poi_address character varying(250) COLLATE pg_catalog."default",
    poi_city character varying(250) COLLATE pg_catalog."default",
    warn_info json[],
    original_item boolean,
    offical_item boolean,
    secret boolean,
    for_friend boolean,
    digged boolean,
    item_comment_status smallint,
    take_down integer,
    effect_stickers character varying(250)[] COLLATE pg_catalog."default",
    private_item boolean,
    duet_enabled boolean,
    stitch_enabled boolean,
    stickers_on_item character varying(250)[] COLLATE pg_catalog."default",
    share_enabled boolean,
    comments character varying(250)[] COLLATE pg_catalog."default",
    duet_display integer,
    stitch_display integer,
    index_enabled boolean,
    diversification_labels character varying(250)[] COLLATE pg_catalog."default",
    diversification_id bigint,
    channel_tags character varying(250)[] COLLATE pg_catalog."default",
    keyword_tags json[],
    is_ai_gc boolean,
    ai_gc_description text COLLATE pg_catalog."default",
    CONSTRAINT "Videos_pkey" PRIMARY KEY (id)
);
END;
