-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.videos
(
    id bigint NOT NULL,
    time_created timestamp without time zone,
    author_id bigint,
    description text,
    hashtags character varying(250)[],
    schedule_time integer,
    location_created character varying(2),
    is_ad boolean,
    suggested_words character varying(250)[],
    diggcount integer,
    sharecount integer,
    commentcount integer,
    playcount integer,
    collectcount integer,
    repostcount integer,
    poi_name character varying(250),
    poi_address character varying(250),
    poi_city character varying(250),
    warn_info json[],
    original_item boolean,
    offical_item boolean,
    secret boolean,
    for_friend boolean,
    digged boolean,
    item_comment_status smallint,
    take_down integer,
    effect_stickers character varying(250),
    private_item boolean,
    duet_enabled boolean,
    stitch_enabled boolean,
    stickers_on_item character varying(250)[],
    share_enabled boolean,
    comments character varying(250)[],
    duet_display integer,
    stitch_display integer,
    index_enabled boolean,
    diversification_labels character varying(250)[],
    diversification_id bigint,
    channel_tags character varying(250)[],
    keyword_tags json[],
    is_ai_gc boolean,
    ai_gc_description text,
    CONSTRAINT "Videos_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.video_files
(
    id bigint NOT NULL,
    filepath path NOT NULL,
    duration integer,
    height integer,
    width integer,
    ratio integer,
    volume_loudness numeric(3, 1),
    volume_peak numeric(6, 5),
    has_original_audio boolean,
    enable_audio_caption boolean,
    no_caption_reason smallint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.scrape_logs
(
    seed_id bigint,
    scraped_last timestamp without time zone,
    downloaded_video boolean,
    encountered_error character varying(1),
    PRIMARY KEY (seed_id)
);

CREATE TABLE IF NOT EXISTS public.music
(
    id bigint,
    title character varying(250),
    author_name character varying(250),
    original boolean,
    schedule_search_time integer,
    collected boolean,
    precise_duration json
);

CREATE TABLE IF NOT EXISTS public.hashtags
(
    name character varying(250),
    id bigint,
    type smallint,
    sub_type smallint,
    is_commerce boolean,
    description text,
    PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public.authors
(
    "Id" bigint,
    username character varying(250),
    name character varying(250),
    signature text,
    create_time integer,
    verified boolean,
    ftc boolean,
    relation integer,
    open_favorite boolean,
    comment_setting integer,
    duet_setting smallint,
    stitch_setting smallint,
    private_account boolean,
    secret boolean,
    is_ad_virtual boolean,
    download_setting smallint,
    recommend_reason character varying(250),
    suggest_account_bind boolean
);

ALTER TABLE IF EXISTS public.video_files
    ADD CONSTRAINT video_id FOREIGN KEY (id)
    REFERENCES public.videos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;